### ISSUE TITLE
Rails: Save

### ISSUE THREAD

**Issue by ritvvijparrikh** [pykih/ProtoGraph.Card.toSocial#8]
- [x] Once Publish button is pressed, hang the screen (modal window with message Please do not refresh, we are still uploading)
- [x] Expose a API Gateway driven API to receive images and upload them to S3 and returns back S3 URL
- [x] Take all the images in the form and call previous method
- [x] Replace Image with URL in form.
- [x] Save the contents of the form in DynamoDB
- [x] Call the API Gateway API to convert DIVtoImage for renderFacebook
- [x] Call the API Gateway API to convert DIVtoImage for renderTwitter
- [x] Call the API Gateway API to convert DIVtoImage for renderInstagram

**Comment by amitbadheka** [comment]
Dependent on https://github.com/pykih/ProtoGraph.Card.toShare/issues/12.

**Comment by amitbadheka** [comment]
We will need to open the api to open for javascript to use. Instead I was thinking we can handle it in schema. We can change the schema to specify the images and which needs to be published to S3. Once published, we can replace the binary image data to s3 url.
